services:
  generate:
    build:
      context: .
      dockerfile: Dockerfile
    image: avianvisitors-generate
    working_dir: /repo/webui/generate
    environment:
      EBIRD_API_KEY: "${EBIRD_API_KEY:-}"
    volumes:
      - ../..:/repo
      - models:/models

volumes:
  models:
