php-version = "8.5"

[source]
paths = ["backend/src", "backend/public", "tests/php", "tests/support"]
includes = ["vendor"]
excludes = ["vendor/nikic/fast-route/test"]

[analyzer]
excludes = ["tests"]

[formatter]
print-width = 120

[linter.rules]
no-error-control-operator = { enabled = false }
no-empty = { enabled = false }
no-isset = { enabled = false }
literal-named-argument = { enabled = false }
cyclomatic-complexity = { enabled = false }
too-many-methods = { enabled = false }
kan-defect = { enabled = false }
halstead = { enabled = false }
excessive-parameter-list = { enabled = false }
no-shorthand-ternary = { enabled = false }
readable-literal = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-else-clause = { enabled = false }
no-empty-catch-clause = { enabled = false }
